### ISSUE TITLE
BUG: Application tab displays 'React Application' instead of LLMStudio logo and name

### ISSUE THREAD

**Issue by MiNeves00** [TensorOpsAI/LLMstudio#12]
### System Info

Browser: Brave v 1.59.117

OS: macOS Ventura 13.5.1

### Description
The browser tab for the application currently displays the default "React Application" text and lacks an icon. 

![Screenshot 2023-10-16 at 14 54 40](https://github.com/TensorOpsAI/LLMstudio/assets/61327611/dba0e6f7-4409-4ba2-a2ed-ee05cea57972)

### Related Components

- [ ] API
- [ ] SDK
- [X] UI

### Reproduction

Open the LLMStudio web application.
Observe the browser tab title and icon.

### Expected behavior

It should instead be branded with the LLMStudio logo and name for better user experience and branding consistency.

**Comment by claudiolemos** [comment]
Done
