### ISSUE TITLE
BUG: version after 0.3.9 can't start ui on macos

### ISSUE THREAD

**Issue by ruanwz** [TensorOpsAI/LLMstudio#166]
### System Info

macos python3.11

### Related Components

- [ ] API
- [ ] SDK
- [X] UI

### Reproduction

install 0.3.9 and run command:
pip install llmstudio==0.3.9 
(llmstudio) ➜  llmstudio llmstudio server --ui       
Running LLMstudio Engine on http://localhost:50001 
Running LLMstudio Tracking on http://localhost:50002 
$ next dev --port 50003
   ▲ Next.js 14.0.3
   - Local:        http://localhost:50003

 ✓ Ready in 1919ms

It didn't work on 0.3.10 to 0.3.12:
(llmstudio) ➜  llmstudio pip install llmstudio==0.3.11
Successfully installed llmstudio-0.3.11
(llmstudio) ➜  llmstudio llmstudio server --ui        
Running LLMstudio Engine on http://localhost:50001 
Running LLMstudio Tracking on http://localhost:50002 
Servers are running. Press CTRL+C to stop.
^CShutting down gracefully...

### Expected behavior

all versions should work with UI

**Comment by MiNeves00** [comment]
Could you see if this issue still persists on v1.0.0?

**Comment by diogoncalves** [comment]
From version 1.0, the UI is no longer part of the llmstudio general release. We'll release an updated UI in the future in a specific project.
