### ISSUE TITLE
FEAT: Auto-Evaluation of batch of tests

### ISSUE THREAD

**Issue by MiNeves00** [TensorOpsAI/LLMstudio#31]
### Feature Request

Tests are running in a batch but they are not being evaluated against the GT answer. 

The evaluation could be done using similarity metrics, LLM or even mathematics.

### Motivation

This would help with quickly testing models and prompts and seeing the result quantified immediately.

### Your contribution

Discussion

**Comment by drkarthi** [comment]
Hi @MiNeves00, I would like to keep track of precision and recall associated with different prompts on a test dataset. Is this issue meant to solve that problem and what is the current status?
