### ISSUE TITLE
FEAT: UI support for Prompt Templating

### ISSUE THREAD

**Issue by MiNeves00** [TensorOpsAI/LLMstudio#53]
### Feature

Support templates like this where the variables can be defined elsewhere so as to not make the text too messy.

"""
I have to understand what is being done here.

In the file API.txt you see all the components that are impacted directly and indirectly from account.

You will see there a flow named UpdateOpportunityStage which is directly impacted.
The source of the flow is in file VS_UpdateOpportunityStage.txt.

file API.txt: {api}

file VS_UpdateOpportunityStage.txt: {text_file}

Questions for example around this flow may be the following, please answer this:

Question: {question}

### Motivation

When actually using the UI for more complex prompt engineering templating is vital to keep the text boxes clean and readable.

### Contribution

Discussion

**Comment by diogoncalves** [comment]
Thank you for your issue.

From version 1.0, the UI is no longer part of the llmstudio general release. We'll release an updated UI in the future in a specific project.

Stay in touch for updates ;)
