### ISSUE TITLE
Set server for the session

### ISSUE THREAD

**Issue by reiid00** [TensorOpsAI/LLMstudio#6]
In the init function, set server for the session and validate it using an http request. Be it in Python Session Level, not local.

**Comment by reiid00** [comment]
PULL Request Made.


Server Session is now being created on a Python Session Level.

API Validation is being done when model is initialized.

API_URL is now dynamic. PATHS are static and based on the model.

**Comment by MiNeves00** [comment]
Can we close? I believe this has been completed.
