### ISSUE TITLE
BUG: docs.llmstudio.ai not reachable

### ISSUE THREAD

**Issue by SaschaHeyer** [TensorOpsAI/LLMstudio#66]
### System Info

not relevant

### Who can help?

@claudiolemos 

### Related Components

- [ ] API
- [ ] SDK
- [ ] UI

### Reproduction

1. Open the GitHub repo
2. Follow the doc link to https://docs.llmstudio.ai/

### Expected behavior

Docs page available

**Comment by claudiolemos** [comment]
Docs website is up! Still a work in progress but will be updated within the following days, API reference is ready
