### ISSUE TITLE
BUG: LLMstudio command not registered on bashrc

### ISSUE THREAD

**Issue by gidutz** [TensorOpsAI/LLMstudio#67]
### System Info

Macbook

### Related Components

- [ ] API
- [x] SDK
- [ ] UI

### Reproduction

❯ pip install LLMstudio
Collecting LLMstudio
  Using cached llmstudio-0.2.19-py3-none-any.whl.metadata (946 bytes)
Requirement already satisfied: pydantic in ./Library/Caches/pypoetry/virtualenvs/poetry-demo-YQizyC9W-py3.12/lib/python3.12/site-packages (from LLMstudio) (2.5.2)
Requirement already satisfied: requests in ./Library/Caches/pypoetry/virtualenvs/poetry-demo-YQizyC9W-py3.12/lib/python3.12/site-packages (from LLMstudio) (2.31.0)
Collecting numpy (from LLMstudio)
  Using cached numpy-1.26.2-cp312-cp312-macosx_11_0_arm64.whl.metadata (61 kB)
INFO: pip is looking at multiple versions of llmstudio to determine which version is compatible with other requirements. This could take a while.
Collecting LLMstudio
  Using cached llmstudio-0.2.18-py3-none-any.whl.metadata (946 bytes)
  Using cached llmstudio-0.2.17-py3-none-any.whl.metadata (967 bytes)
  Using cached llmstudio-0.2.16-py3-none-any.whl.metadata (967 bytes)
  Using cached llmstudio-0.2.15-py3-none-any.whl.metadata (967 bytes)
  Using cached llmstudio-0.2.14-py3-none-any.whl.metadata (967 bytes)
  Using cached llmstudio-0.2.13-py3-none-any.whl.metadata (967 bytes)
  Using cached llmstudio-0.2.12-py3-none-any.whl.metadata (967 bytes)
INFO: pip is still looking at multiple versions of llmstudio to determine which version is compatible with other requirements. This could take a while.
  Using cached llmstudio-0.2.11-py3-none-any.whl.metadata (934 bytes)
  Using cached llmstudio-0.2.10-py3-none-any.whl.metadata (928 bytes)
  Using cached llmstudio-0.2.9-py3-none-any.whl.metadata (927 bytes)
  Using cached llmstudio-0.2.8-py3-none-any.whl.metadata (851 bytes)
  Using cached llmstudio-0.2.7-py3-none-any.whl.metadata (826 bytes)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Using cached llmstudio-0.2.6-py3-none-any.whl.metadata (826 bytes)
  Using cached llmstudio-0.2.5-py3-none-any.whl.metadata (826 bytes)
  Using cached llmstudio-0.2.4-py3-none-any.whl.metadata (826 bytes)
  Using cached llmstudio-0.2.3-py3-none-any.whl.metadata (826 bytes)
  Using cached llmstudio-0.2.2-py3-none-any.whl.metadata (826 bytes)
  Using cached llmstudio-0.2.1-py3-none-any.whl.metadata (826 bytes)
  Using cached llmstudio-0.2.0-py3-none-any.whl.metadata (771 bytes)
  Using cached llmstudio-0.1.6-py3-none-any.whl.metadata (497 bytes)
Requirement already satisfied: annotated-types>=0.4.0 in ./Library/Caches/pypoetry/virtualenvs/poetry-demo-YQizyC9W-py3.12/lib/python3.12/site-packages (from pydantic->LLMstudio) (0.6.0)
Requirement already satisfied: pydantic-core==2.14.5 in ./Library/Caches/pypoetry/virtualenvs/poetry-demo-YQizyC9W-py3.12/lib/python3.12/site-packages (from pydantic->LLMstudio) (2.14.5)
Requirement already satisfied: typing-extensions>=4.6.1 in ./Library/Caches/pypoetry/virtualenvs/poetry-demo-YQizyC9W-py3.12/lib/python3.12/site-packages (from pydantic->LLMstudio) (4.8.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./Library/Caches/pypoetry/virtualenvs/poetry-demo-YQizyC9W-py3.12/lib/python3.12/site-packages (from requests->LLMstudio) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in ./Library/Caches/pypoetry/virtualenvs/poetry-demo-YQizyC9W-py3.12/lib/python3.12/site-packages (from requests->LLMstudio) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./Library/Caches/pypoetry/virtualenvs/poetry-demo-YQizyC9W-py3.12/lib/python3.12/site-packages (from requests->LLMstudio) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in ./Library/Caches/pypoetry/virtualenvs/poetry-demo-YQizyC9W-py3.12/lib/python3.12/site-packages (from requests->LLMstudio) (2023.11.17)
Using cached llmstudio-0.1.6-py3-none-any.whl (12 kB)
Installing collected packages: LLMstudio
Successfully installed LLMstudio-0.1.6

LLMstudio server --ui
zsh: command not found: LLMstudio

### Expected behavior

We'd like to see LLMstudio run after pip install however it gives an error: zsh: command not found: LLMstudio

**Comment by gidutz** [comment]
Hey @sagarmj-cloud 

Thank you again for reaching out and reporting the issue you've encountered with the LLMstudio command not being found after installation. I understand how frustrating such issues can be and I'm here to assist you in resolving it. Based on your description, there are a couple of common reasons that might be causing this problem:

- Environment Path Issue: The LLMstudio command may not be recognized if the Python script directory where it's installed isn't included in your system's PATH. The PATH is a list of directories where the system looks for executable files. If the directory where LLMstudio is installed isn't in this list, your shell (zsh) won't be able to find and execute the command.
- Virtual Environment Issue: If LLMstudio was installed within a virtual environment and you're trying to access it outside of that environment, the command won't be recognized. This is because each virtual environment has its own set of installed packages and paths.



To better assist you, could you please provide the following additional information?

1. **Installation Method**: Did you install LLMstudio within a virtual environment or was it a global installation? If it was within a virtual environment, ensure you activate that environment before running the command.
2. **Python Version**: Which version of Python are you using? The LLMstudio package requires a specific Python version, so confirming this would be helpful.
3. **Path Verification**: After installation, did you check if the Python script directory is included in your system's PATH? You can do this by running echo $PATH in your terminal.
4. **Installation Output**: Could you provide the complete output of the LLMstudio installation process? This would help in identifying if there were any warnings or errors during installation.
5. **System Information**: Information about your operating system (e.g., macOS version) would be useful.

Once you provide this information, we'll be in a better position to diagnose the issue more accurately and guide you towards a resolution. Your cooperation is greatly appreciated, and we're committed to helping you resolve this issue promptly.

**Comment by sagarmj-cloud** [comment]
Hello @gidutz  - Thank you for the prompt reply - enclosing the answers here to all your question - 

**Installation Method:** Did you install LLMstudio within a virtual environment or was it a global installation? If it was within a virtual environment, ensure you activate that environment before running the command.
- This was a global installation using pipx

**Python Version:** Which version of Python are you using? The LLMstudio package requires a specific Python version, so confirming this would be helpful. - 
- I am using Python3 - version 3.12.0

**Path Verification:** After installation, did you check if the Python script directory is included in your system's PATH? You can do this by running echo $PATH in your terminal.
- I just verified the path and looks like this - 
- `❯ clear
❯ pipx install LLMstudio --include-deps
⚠️  Note: normalizer was already on your PATH at /opt/homebrew/bin/normalizer
  installed package llmstudio 0.1.6, installed using Python 3.12.0
  These apps are now globally available
    - normalizer
done! ✨ 🌟 ✨
❯ echo $PATH
/Users/sagarjadhav/.pyenv/shims:/Users/sagarjadhav/.sdkman/candidates/java/current/bin:/Library/Frameworks/Python.framework/Versions/3.12/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/sagarjadhav/.local/bin:/Users/sagarjadhav/.local/bin`

**Installation Output:** Could you provide the complete output of the LLMstudio installation process? This would help in identifying if there were any warnings or errors during installation. 
- I think it was a successful installation.

**System Information:** Information about your operating system (e.g., macOS version) would be useful.
I am using the latest MacOsX - 14.1.2 Sonoma

**Comment by MiNeves00** [comment]
From the last message on your installation it appears that a older version is being installed: 
`Successfully installed LLMstudio-0.1.6`


Could yoy try forcing the version number by doing the following and checking if this fixes it?

`pip uninstall llmstudio`
`pip install llmstudio==0.2.20`

**Comment by sagarmj-cloud** [comment]
Yes this worked for me. Thank you. I am able to get the UI working with the steps you have mentioned and able to see everything in action.
    On Thursday, December 7, 2023 at 02:17:54 AM PST, Miguel Neves ***@***.***> wrote:  
 
 


From the last message on your installation it appears that a older version is being installed:
Successfully installed LLMstudio-0.1.6

Could yoy try forcing the version number by doing the following and checking if this fixes it?

pip uninstall llmstudio
pip install llmstudio==0.2.20
