### ISSUE TITLE
BUG: AttributeError in validate_parameters Method ('OpenAIParameters' object has no attribute 'model_dump')

### ISSUE THREAD

**Issue by niklas-kammertons** [TensorOpsAI/LLMstudio#70]
### System Info

Google Colab
unsing:
!pip install LLMstudio

### Related Components

- [ ] API
- [X] SDK
- [ ] UI

### Reproduction

Encountered a bug while running the 01_intro_to_llmstudio.ipynb notebook from the LLMstudio repository on Colab.
Relevant notebook URL: [Intro to LLMstudio Notebook](https://github.com/TensorOpsAI/LLMstudio/blob/main/examples/01_intro_to_llmstudio.ipynb)

Issue:
An AttributeError is thrown in the validate_parameters method of the OpenAIParameters class.
The error message indicates a missing model_dump method: AttributeError: 'OpenAIParameters' object has no attribute 'model_dump'.

Code References:
File Path: LLMstudio/llmstudio/models/openai.py
Method: validate_parameters
File Path: LLMstudio/llmstudio/validators/openai.py
Class: OpenAIParameters

Steps to Reproduce:

1. Open the 01_intro_to_llmstudio.ipynb notebook in Google Colab.
2. !pip install LLMstudio
3. Execute the notebook cells in order.
4. Observe the AttributeError upon reaching the cell that invokes validate_parameters.

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input> in <cell line: 2>()
      1 # OpenAI models
----> 2 gpt_3 = openai_client.get_model("gpt-3.5-turbo")
      3 gpt_4 = openai_client.get_model("gpt-4")

4 frames
/usr/local/lib/python3.10/dist-packages/llmstudio/models/openai.py in validate_parameters(self, parameters)
     81             """
     82             parameters = parameters or {}
---> 83             return OpenAIParameters(**parameters).model_dump()
     84 
     85     class GPT3_5(OpenAIModel):

AttributeError: 'OpenAIParameters' object has no attribute 'model_dump'
```

### Expected behavior

Correctly loading the models

**Comment by claudiolemos** [comment]
Hey @niklas-kammertons, going over the error I'm pretty sure it's due to Pydantic version, you probably have an older version. Can you create a conda env and do a clean install of llmstudio and retry?

**Comment by claudiolemos** [comment]
should be fixed in new upgrade to support both pydantics. can you do pip install --upgrade llmstudio and test
