### ISSUE TITLE
FEAT: Google Colab Support for LLMstudio Web UI

### ISSUE THREAD

**Issue by niklas-kammertons** [TensorOpsAI/LLMstudio#71]
### Feature Request

Request for the addition of Google Colab support for the LLMstudio Web UI.

I know that it's technically possible, as other projects use gradio for spawning web UI out of colab instance (e.g. https://github.com/lllyasviel/Fooocus)

### Motivation

This feature would greatly enhance the usability and accessibility of LLMstudio for a broader range of users and remove any entry barriers to trying the tool. If the UI could be hosted in colab I could even recommend and explain how to use it in 5min to any "non-tech colleagues" for prompt engineering or prototyping an LLM idea for their department's use case.

Having the LLMstudio UI to track and evaluate OpenAI API calls would be a great asset for all LLM projects being developed in Colab (from personal use hobby projects to university student project colabs or rapid prototyping efforts inside of organizations).

### Your contribution

Unfortunately, I have no gradio experience or knowledge how to technically solve this.

**Comment by gidutz** [comment]
Running servers with UI inside Google Colab is always a challenge. 
A possible solution is to allow remote hosting of LLMstudio like MLflow has with remote community servers.

**Comment by diogoncalves** [comment]
Thank you for your issue.

From version 1.0, the UI is no longer part of the llmstudio general release. We'll release an updated UI in the future in a specific project.

However, you can now run LLMstudio in Google Colab: https://colab.research.google.com/drive/1aL49CGOLHvwbnM0RA4ht5IX1IIg-Tg1n?usp=sharing 

Stay in touch for updates ;)
