### ISSUE TITLE
BUG: problem with loading the UI

### ISSUE THREAD

**Issue by gidutz** [TensorOpsAI/LLMstudio#74]
### System Info

installed bun

### Related Components

- [ ] API
- [ ] SDK
- [X] UI

### Reproduction

llmstudio server --ui 
Running UI on localhost:8000
Running Engine on localhost:8000
No package.json, so nothing to update
Running Tracking on http://localhost:8080
Error running the UI app: Command '['bun', 'update']' returned non-zero exit status 1.
INFO:     Started server process [3755]
INFO:     Waiting for application startup.
INFO:     Started server process [3755]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
INFO:     Uvicorn running on http://localhost:8080 (Press CTRL+C to quit)

### Expected behavior

the UI should load

**Comment by claudiolemos** [comment]
Fixed with the latest commit. Just upgrade to the latest version
`pip install --upgrade llmstudio`
